package boatstack

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func testConfig() ProjectConfig {
	return ProjectConfig{
		SchemaVersion: 1,
		Project: Project{
			Name: "fixture", Commands: map[string]string{"test": "go test ./..."},
		},
		Workflow: Workflow{HumanPlanApproval: true, IndependentReviewForHighRisk: true, AllowPassWithGaps: true},
		Adapters: []string{"cursor", "claude", "codex", "github"},
		Integrations: map[string]IntegrationState{
			"gstack":   {Requested: false, Version: GStackRef},
			"spec-kit": {Requested: false, Version: SpecKitVersion},
		},
	}
}

func TestExportAndDriftCheck(t *testing.T) {
	repo := t.TempDir()
	config := testConfig()
	raw, err := MarshalJSON(config)
	if err != nil {
		t.Fatal(err)
	}
	bundle, err := BuildExportBundle(".boatstack-project.json", config, raw, "boatstack")
	if err != nil {
		t.Fatal(err)
	}
	if err := WriteExport(repo, bundle.Files); err != nil {
		t.Fatal(err)
	}
	if err := CheckExport(repo, bundle.Files); err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{
		".cursor/commands/plan-gate.md",
		".cursor/commands/review.md",
		".claude/skills/boatstack/SKILL.md",
		".agents/skills/boatstack/SKILL.md",
		".product-loop/.gitignore",
		".product-loop/templates/plan.md",
		".product-loop/templates/approval.md",
	} {
		if !fileExists(filepath.Join(repo, filepath.FromSlash(path))) {
			t.Fatalf("expected generated file %s", path)
		}
	}
	if _, exists := bundle.Files[".product-loop/tools/approve_plan.py"]; exists {
		t.Fatal("public export must not contain Python runtime tools")
	}
	if _, exists := bundle.Files[".product-loop/templates/plan.json"]; exists {
		t.Fatal("Markdown-native planning must not export plan.json")
	}
	autoPlan := string(bundle.Files[".cursor/commands/auto-plan.md"])
	planGate := string(bundle.Files[".cursor/commands/plan-gate.md"])
	build := string(bundle.Files[".cursor/commands/build.md"])
	if !strings.Contains(autoPlan, "Markdown-only") || !strings.Contains(autoPlan, "never silently choose a default") || !strings.Contains(autoPlan, "planning-write") || !strings.Contains(autoPlan, "PROPOSED") {
		t.Fatal("auto-plan adapter does not enforce the Markdown and question boundaries")
	}
	if !strings.Contains(planGate, "approval.md") || !strings.Contains(planGate, "Remain in Plan mode") || !strings.Contains(planGate, "record-approval") {
		t.Fatal("plan-gate adapter does not keep approval in Plan mode")
	}
	if !strings.Contains(build, "activate-plan") || !strings.Contains(build, "READY_FOR_BUILD") || !strings.Contains(build, "without activating") || strings.Contains(build, "compile-plan") {
		t.Fatal("build adapter must activate the Markdown plan exactly once")
	}
	ship := string(bundle.Files[".cursor/commands/ship-gate.md"])
	if !strings.Contains(ship, "separate repair PR") || !strings.Contains(ship, "Never edit unrelated code") {
		t.Fatal("ship adapter permits unrelated scope expansion")
	}
	lock := string(bundle.Files[".product-loop/generated.lock.json"])
	if !strings.Contains(lock, `"source_commit"`) || !strings.Contains(lock, `"integrations"`) {
		t.Fatal("generated lock must record runtime provenance and integrations")
	}
}

func TestExportRefusesUserOwnedCollision(t *testing.T) {
	repo := t.TempDir()
	path := filepath.Join(repo, ".cursor", "rules", "boatstack.mdc")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("user owned\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	config := testConfig()
	raw, _ := MarshalJSON(config)
	bundle, err := BuildExportBundle("config.json", config, raw, "boatstack")
	if err != nil {
		t.Fatal(err)
	}
	if err := WriteExport(repo, bundle.Files); err == nil || !strings.Contains(err.Error(), "user-owned") {
		t.Fatalf("expected user-owned collision, got %v", err)
	}
	value, _ := os.ReadFile(path)
	if string(value) != "user owned\n" {
		t.Fatal("collision handling modified the user-owned file")
	}
}

func TestExportAdoptsLegacyGeneratedFiles(t *testing.T) {
	repo := t.TempDir()
	path := filepath.Join(repo, ".cursor", "rules", "boatstack.mdc")
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	legacy := "<!-- Generated by product-engineering-loop exporter. Do not edit; change canonical source or project.json. -->\n"
	if err := os.WriteFile(path, []byte(legacy), 0o644); err != nil {
		t.Fatal(err)
	}
	config := testConfig()
	raw, _ := MarshalJSON(config)
	bundle, err := BuildExportBundle("config.json", config, raw, "boatstack")
	if err != nil {
		t.Fatal(err)
	}
	if err := WriteExport(repo, bundle.Files); err != nil {
		t.Fatalf("legacy generated file should be safely replaceable: %v", err)
	}
}

func TestExportRemovesOnlyUnmodifiedStaleGeneratedPath(t *testing.T) {
	repo := t.TempDir()
	config := testConfig()
	raw, _ := MarshalJSON(config)
	bundle, _ := BuildExportBundle("config.json", config, raw, "boatstack")
	if err := WriteExport(repo, bundle.Files); err != nil {
		t.Fatal(err)
	}
	stale := ".cursor/commands/retro.md"
	delete(bundle.Files, stale)
	if err := WriteExport(repo, bundle.Files); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(repo, filepath.FromSlash(stale))); !os.IsNotExist(err) {
		t.Fatal("unmodified stale generated path was not removed")
	}
}
