package boatstack

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const hookCommandMarker = ".product-loop/hooks/guard"

func guardShellScript() []byte {
	return []byte(fmt.Sprintf(`#!/usr/bin/env bash
# Generated by Boatstack. Do not edit; change canonical source or .boatstack-project.json.
set -u

HOST="${1:-}"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$ROOT" ]]; then
  echo "Boatstack safety guard could not resolve the repository; denying tool execution." >&2
  exit 2
fi

COMMON="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null || true)"
if [[ -z "$COMMON" ]]; then
  echo "Boatstack safety guard could not resolve the Git common directory; denying tool execution." >&2
  exit 2
fi

case "$(uname -s)" in
  Darwin) OS_NAME="darwin"; EXTENSION="" ;;
  Linux) OS_NAME="linux"; EXTENSION="" ;;
  MINGW*|MSYS*|CYGWIN*) OS_NAME="windows"; EXTENSION=".exe" ;;
  *) echo "Boatstack safety guard found an unsupported operating system; denying tool execution." >&2; exit 2 ;;
esac
case "$(uname -m)" in
  x86_64|amd64) ARCH="amd64" ;;
  arm64|aarch64) ARCH="arm64" ;;
  *) echo "Boatstack safety guard found an unsupported architecture; denying tool execution." >&2; exit 2 ;;
esac

HELPER="$COMMON/boatstack/runtimes/%s/%s/${OS_NAME}-${ARCH}/boatstack-helper${EXTENSION}"
MANIFEST="$COMMON/boatstack/runtimes/%s/%s/${OS_NAME}-${ARCH}/runtime.lock.json"
if [[ ! -x "$HELPER" ]]; then
  echo "Boatstack shared runtime is missing; run the verified installer once from any checkout in this Git clone." >&2
  exit 2
fi
if [[ -L "$HELPER" || ! -f "$MANIFEST" || -L "$MANIFEST" ]]; then
  echo "Boatstack shared runtime is unsafe or incomplete; rerun the verified tagged installer." >&2
  exit 2
fi
EXPECTED="$(sed -n 's/.*"binary_sha256"[[:space:]]*:[[:space:]]*"\([0-9a-f]\{64\}\)".*/\1/p' "$MANIFEST" | head -n 1)"
if command -v sha256sum >/dev/null 2>&1; then
  ACTUAL="$(sha256sum "$HELPER" | awk '{print $1}')"
elif command -v shasum >/dev/null 2>&1; then
  ACTUAL="$(shasum -a 256 "$HELPER" | awk '{print $1}')"
else
  echo "Boatstack cannot verify the shared runtime checksum; denying tool execution." >&2
  exit 2
fi
if [[ -z "$EXPECTED" || "$ACTUAL" != "$EXPECTED" ]]; then
  echo "Boatstack shared runtime checksum is invalid; rerun the verified tagged installer." >&2
  exit 2
fi

exec "$HELPER" bootstrap-safety-hook --host "$HOST" --repo "$ROOT"
`, Version, SourceCommit, Version, SourceCommit))
}

func guardPowerShellScript() []byte {
	return []byte(fmt.Sprintf(`# Generated by Boatstack. Do not edit; change canonical source or .boatstack-project.json.
param([Parameter(Mandatory=$true)][string]$HostName)
$ErrorActionPreference = "Stop"
$root = (& git rev-parse --show-toplevel 2>$null)
if (-not $root) {
  [Console]::Error.WriteLine("Boatstack safety guard could not resolve the repository; denying tool execution.")
  exit 2
}
$common = (& git rev-parse --path-format=absolute --git-common-dir 2>$null)
if (-not $common) {
  [Console]::Error.WriteLine("Boatstack safety guard could not resolve the Git common directory; denying tool execution.")
  exit 2
}
$architecture = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString().ToLowerInvariant()
$arch = switch ($architecture) {
  "x64" { "amd64" }
  "arm64" { "arm64" }
  default {
    [Console]::Error.WriteLine("Boatstack safety guard found an unsupported architecture; denying tool execution.")
    exit 2
  }
}
$helper = Join-Path $common "boatstack/runtimes/%s/%s/windows-$arch/boatstack-helper.exe"
$manifestPath = Join-Path $common "boatstack/runtimes/%s/%s/windows-$arch/runtime.lock.json"
if (-not (Test-Path -LiteralPath $helper -PathType Leaf)) {
  [Console]::Error.WriteLine("Boatstack shared runtime is missing; run the verified installer once from any checkout in this Git clone.")
  exit 2
}
$helperInfo = Get-Item -LiteralPath $helper
if (($helperInfo.Attributes -band [IO.FileAttributes]::ReparsePoint) -or -not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
  [Console]::Error.WriteLine("Boatstack shared runtime is unsafe or incomplete; rerun the verified tagged installer.")
  exit 2
}
$manifestInfo = Get-Item -LiteralPath $manifestPath
if ($manifestInfo.Attributes -band [IO.FileAttributes]::ReparsePoint) {
  [Console]::Error.WriteLine("Boatstack shared runtime manifest is unsafe; rerun the verified tagged installer.")
  exit 2
}
try {
  $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
  $actual = (Get-FileHash -LiteralPath $helper -Algorithm SHA256).Hash.ToLowerInvariant()
} catch {
  [Console]::Error.WriteLine("Boatstack could not verify the shared runtime; denying tool execution.")
  exit 2
}
if (-not $manifest.binary_sha256 -or $actual -ne $manifest.binary_sha256.ToLowerInvariant()) {
  [Console]::Error.WriteLine("Boatstack shared runtime checksum is invalid; rerun the verified tagged installer.")
  exit 2
}
& $helper bootstrap-safety-hook --host $HostName --repo $root
exit $LASTEXITCODE
`, Version, SourceCommit, Version, SourceCommit))
}

func hookCommand(host string) string {
	return `bash "$(git rev-parse --show-toplevel)/.product-loop/hooks/guard.sh" ` + host
}

func hookCommandWindows(host string) string {
	return `powershell -NoProfile -ExecutionPolicy Bypass -Command "$r = & git rev-parse --show-toplevel; & (Join-Path $r '.product-loop/hooks/guard.ps1') ` + host + `"`
}

func desiredHostHookForEvent(host, event string) map[string]any {
	switch host {
	case "cursor":
		return map[string]any{
			"command": hookCommand(host), "commandWindows": hookCommandWindows(host),
			"failClosed": true, "timeout": 10,
		}
	case "claude":
		return map[string]any{
			"matcher": "Bash|Shell|mcp__.*",
			"hooks": []any{map[string]any{
				"type": "command", "command": hookCommand(host),
				"timeout": 10, "statusMessage": "Checking Boatstack execution policy",
			}},
		}
	case "codex":
		return map[string]any{
			"matcher": "Bash|Shell|mcp__.*",
			"hooks": []any{map[string]any{
				"type": "command", "command": hookCommand(host), "commandWindows": hookCommandWindows(host),
				"timeout": 10, "statusMessage": "Checking Boatstack execution policy",
			}},
		}
	default:
		return map[string]any{}
	}
}

func hookEvents(host string) []string {
	if host == "cursor" {
		return []string{"beforeShellExecution", "beforeMCPExecution"}
	}
	return []string{"PreToolUse"}
}

func desiredHostHook(host string) map[string]any {
	return desiredHostHookForEvent(host, hookEvents(host)[0])
}

func hookFragmentJSON(host string) ([]byte, error) {
	events := map[string]any{}
	for _, event := range hookEvents(host) {
		events[event] = desiredHostHookForEvent(host, event)
	}
	return GeneratedJSON(map[string]any{"schema_version": 1, "host": host, "events": events})
}

func hostHookConfigPath(repo, host string) string {
	switch host {
	case "cursor":
		return filepath.Join(repo, ".cursor", "hooks.json")
	case "claude":
		return filepath.Join(repo, ".claude", "settings.json")
	case "codex":
		return filepath.Join(repo, ".codex", "hooks.json")
	default:
		return ""
	}
}

func HostHookPaths(adapters []string) []string {
	paths := []string{}
	for _, host := range []string{"cursor", "claude", "codex"} {
		if contains(adapters, host) {
			paths = append(paths, filepath.ToSlash(strings.TrimPrefix(hostHookConfigPath("", host), string(filepath.Separator))))
		}
	}
	return paths
}

func containsBoatstackHook(value any) bool {
	switch typed := value.(type) {
	case string:
		return strings.Contains(typed, hookCommandMarker)
	case []any:
		for _, item := range typed {
			if containsBoatstackHook(item) {
				return true
			}
		}
	case map[string]any:
		for _, item := range typed {
			if containsBoatstackHook(item) {
				return true
			}
		}
	}
	return false
}

func loadHookConfig(path string) (map[string]any, error) {
	value, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return map[string]any{}, nil
	}
	if err != nil {
		return nil, err
	}
	config := map[string]any{}
	if err := DecodeJSON("load host hook configuration", path, value, &config); err != nil {
		return nil, err
	}
	return config, nil
}

func mergeHostHook(config map[string]any, host string) error {
	hooks, ok := config["hooks"].(map[string]any)
	if config["hooks"] == nil {
		hooks = map[string]any{}
		config["hooks"] = hooks
	} else if !ok {
		return fmt.Errorf("host hook config has non-object hooks")
	}
	for _, event := range hookEvents(host) {
		entries := []any{}
		if existing := hooks[event]; existing != nil {
			var entriesOK bool
			entries, entriesOK = existing.([]any)
			if !entriesOK {
				return fmt.Errorf("host hook event %s is not a list", event)
			}
		}
		kept := []any{}
		found := 0
		for _, entry := range entries {
			if containsBoatstackHook(entry) {
				found++
				continue
			}
			kept = append(kept, entry)
		}
		if found > 1 {
			return fmt.Errorf("ambiguous Boatstack hook collision in %s", event)
		}
		kept = append(kept, desiredHostHookForEvent(host, event))
		hooks[event] = kept
	}
	if host == "cursor" && config["version"] == nil {
		config["version"] = float64(1)
	}
	return nil
}

func InstallHostHooks(repo string, adapters []string) error {
	prepared, err := PrepareHostHooks(repo, adapters)
	if err != nil {
		return err
	}
	for _, path := range sortedKeys(prepared) {
		if err := atomicWrite(path, prepared[path]); err != nil {
			return err
		}
	}
	return nil
}

// PrepareHostHooks renders and validates every selected host document without
// writing, allowing initialization to fail before entering its commit phase.
func PrepareHostHooks(repo string, adapters []string) (map[string][]byte, error) {
	prepared := map[string][]byte{}
	for _, host := range []string{"cursor", "claude", "codex"} {
		if !contains(adapters, host) {
			continue
		}
		path := hostHookConfigPath(repo, host)
		config, err := loadHookConfig(path)
		if err != nil {
			return nil, err
		}
		if err := mergeHostHook(config, host); err != nil {
			return nil, fmt.Errorf("prepare %s host hooks in %s: %w", host, path, err)
		}
		value, err := MarshalJSON(config)
		if err != nil {
			return nil, fmt.Errorf("serialize merged host hook configuration %s: %w", path, err)
		}
		if err := ValidateJSON("validate merged host hook configuration", path, value); err != nil {
			return nil, err
		}
		prepared[path] = value
	}
	return prepared, nil
}

func CheckHostHooks(repo string, adapters []string) error {
	return checkHostHooks(repo, adapters, func(host, event string) (any, error) {
		return desiredHostHookForEvent(host, event), nil
	})
}

// CheckInstalledHostHooks validates merged host settings against the committed
// fragment from the installed release. Update preflight must use this boundary:
// comparing an old, healthy hook with the incoming release template would
// misclassify an intentional template migration as user drift.
func CheckInstalledHostHooks(repo string, adapters []string) error {
	fragments := map[string]map[string]any{}
	return checkHostHooks(repo, adapters, func(host, event string) (any, error) {
		fragment := fragments[host]
		if fragment == nil {
			path := filepath.Join(repo, ".product-loop", "hooks", host+".fragment.json")
			value, err := os.ReadFile(path)
			if err != nil {
				return nil, fmt.Errorf("cannot read installed %s hook fragment: %w", host, err)
			}
			if err := DecodeJSON("load installed host hook fragment", path, value, &fragment); err != nil {
				return nil, err
			}
			if fragment["schema_version"] != float64(1) || fragment["host"] != host {
				return nil, fmt.Errorf("invalid installed %s hook fragment identity", host)
			}
			fragments[host] = fragment
		}
		events, ok := fragment["events"].(map[string]any)
		if !ok || events[event] == nil {
			return nil, fmt.Errorf("installed %s hook fragment is missing %s", host, event)
		}
		return events[event], nil
	})
}

func checkHostHooks(repo string, adapters []string, expectedForEvent func(host, event string) (any, error)) error {
	for _, host := range []string{"cursor", "claude", "codex"} {
		if !contains(adapters, host) {
			continue
		}
		path := hostHookConfigPath(repo, host)
		config, err := loadHookConfig(path)
		if err != nil {
			return err
		}
		hooks, ok := config["hooks"].(map[string]any)
		if !ok {
			return fmt.Errorf("missing %s hooks in %s", host, path)
		}
		for _, event := range hookEvents(host) {
			expectedEntry, err := expectedForEvent(host, event)
			if err != nil {
				return err
			}
			entries, ok := hooks[event].([]any)
			if !ok {
				return fmt.Errorf("missing %s safety event %s in %s", host, event, path)
			}
			matches := 0
			for _, entry := range entries {
				if containsBoatstackHook(entry) {
					matches++
					current, _ := json.Marshal(entry)
					expected, _ := json.Marshal(expectedEntry)
					if string(current) != string(expected) {
						return fmt.Errorf("drifted %s Boatstack safety hook", host)
					}
				}
			}
			if matches != 1 {
				return fmt.Errorf("expected exactly one %s Boatstack safety hook for %s; found %d", host, event, matches)
			}
		}
	}
	return nil
}
