package boatstack

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

const hookCommandMarker = ".product-loop/hooks/guard"

type HookDiagnostic struct {
	Host              string
	ContractStatus    string
	LiveEventObserved bool
}

func canonicalHookEvent(host string) ([]byte, error) {
	switch host {
	case "cursor":
		return []byte(`{"hook_event_name":"beforeShellExecution","command":"git status --short"}`), nil
	case "claude", "codex":
		return []byte(`{"hook_event_name":"PreToolUse","tool_name":"Bash","tool_input":{"command":"git status --short"}}`), nil
	case "gemini":
		return []byte(`{"hook_event_name":"BeforeTool","tool_name":"run_shell_command","tool_input":{"command":"git status --short"}}`), nil
	default:
		return nil, fmt.Errorf("unsupported hook host %q; expected cursor, claude, codex, or gemini", host)
	}
}

func validateCanonicalHookOutput(host string, output []byte) error {
	if host == "cursor" {
		var decision map[string]any
		if err := json.Unmarshal(bytes.TrimSpace(output), &decision); err != nil || stringValue(decision["permission"]) != "allow" {
			return fmt.Errorf("cursor hook diagnostic returned a malformed or non-allow response")
		}
		return nil
	}
	if host == "gemini" {
		var decision map[string]any
		if err := json.Unmarshal(bytes.TrimSpace(output), &decision); err != nil || stringValue(decision["decision"]) != "allow" {
			return fmt.Errorf("gemini hook diagnostic returned a malformed or non-allow response")
		}
		return nil
	}
	if len(bytes.TrimSpace(output)) != 0 {
		return fmt.Errorf("%s hook diagnostic returned unexpected allow output", host)
	}
	return nil
}

var hookDiagnosticRunner = runInstalledHookDiagnostic

func runInstalledHookDiagnostic(ctx context.Context, repo, host string, input []byte) ([]byte, error) {
	var command *exec.Cmd
	if runtime.GOOS == "windows" {
		path := filepath.Join(repo, ".product-loop", "hooks", "guard.ps1")
		command = exec.CommandContext(ctx, "powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", path, "-HostName", host)
	} else {
		path := filepath.Join(repo, ".product-loop", "hooks", "guard.sh")
		command = exec.CommandContext(ctx, "bash", path, host)
	}
	command.Dir = repo
	command.Stdin = bytes.NewReader(append(input, '\n'))
	channels, err := runCommandChannels(command)
	if err != nil {
		return channels.Stdout, commandFailure(channels, err)
	}
	return channels.Stdout, nil
}

// DiagnoseHook runs the installed guard with a canonical, read-only event. It
// proves the generated wrapper, shared runtime, decoder, and allow contract; it
// deliberately cannot observe the coding host's live event payload.
func DiagnoseHook(repoPath, hostName string) (HookDiagnostic, error) {
	host := strings.ToLower(strings.TrimSpace(hostName))
	input, err := canonicalHookEvent(host)
	if err != nil {
		return HookDiagnostic{}, err
	}
	repo, err := ResolveRepository(repoPath)
	if err != nil {
		return HookDiagnostic{}, err
	}

	ctx, cancel := context.WithTimeout(context.Background(), 12*time.Second)
	defer cancel()
	output, runErr := hookDiagnosticRunner(ctx, repo, host, input)
	if ctx.Err() != nil {
		return HookDiagnostic{}, fmt.Errorf("%s hook diagnostic timed out", host)
	}
	if runErr != nil {
		detail := boundedObservation(strings.TrimSpace(string(output) + " " + runErr.Error()))
		return HookDiagnostic{}, fmt.Errorf("%s hook diagnostic failed: %s", host, detail)
	}
	if err := validateCanonicalHookOutput(host, output); err != nil {
		return HookDiagnostic{}, err
	}
	return HookDiagnostic{Host: host, ContractStatus: "PASS", LiveEventObserved: false}, nil
}

func guardShellScript() []byte {
	return []byte(fmt.Sprintf(`#!/usr/bin/env bash
# Generated by Boatstack. Do not edit; change canonical source or .boatstack-project.json.
set -u

HOST="${1:-}"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$ROOT" ]]; then
  echo "Boatstack safety guard could not resolve the repository; denying tool execution." >&2
  exit 2
fi

COMMON="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null || true)"
if [[ -z "$COMMON" ]]; then
  echo "Boatstack safety guard could not resolve the Git common directory; denying tool execution." >&2
  exit 2
fi

case "$(uname -s)" in
  Darwin) OS_NAME="darwin"; EXTENSION="" ;;
  Linux) OS_NAME="linux"; EXTENSION="" ;;
  MINGW*|MSYS*|CYGWIN*) OS_NAME="windows"; EXTENSION=".exe" ;;
  *) echo "Boatstack safety guard found an unsupported operating system; denying tool execution." >&2; exit 2 ;;
esac
case "$(uname -m)" in
  x86_64|amd64) ARCH="amd64" ;;
  arm64|aarch64) ARCH="arm64" ;;
  *) echo "Boatstack safety guard found an unsupported architecture; denying tool execution." >&2; exit 2 ;;
esac

HELPER="$COMMON/boatstack/runtimes/%s/%s/${OS_NAME}-${ARCH}/boatstack-helper${EXTENSION}"
MANIFEST="$COMMON/boatstack/runtimes/%s/%s/${OS_NAME}-${ARCH}/runtime.lock.json"
if [[ ! -x "$HELPER" ]]; then
  echo "Boatstack shared runtime is missing; run the verified installer once from any checkout in this Git clone." >&2
  exit 2
fi
if [[ -L "$HELPER" || ! -f "$MANIFEST" || -L "$MANIFEST" ]]; then
  echo "Boatstack shared runtime is unsafe or incomplete; rerun the verified tagged installer." >&2
  exit 2
fi
EXPECTED="$(sed -n 's/.*"binary_sha256"[[:space:]]*:[[:space:]]*"\([0-9a-f]\{64\}\)".*/\1/p' "$MANIFEST" | head -n 1)"
if command -v sha256sum >/dev/null 2>&1; then
  ACTUAL="$(sha256sum "$HELPER" | awk '{print $1}')"
elif command -v shasum >/dev/null 2>&1; then
  ACTUAL="$(shasum -a 256 "$HELPER" | awk '{print $1}')"
else
  echo "Boatstack cannot verify the shared runtime checksum; denying tool execution." >&2
  exit 2
fi
if [[ -z "$EXPECTED" || "$ACTUAL" != "$EXPECTED" ]]; then
  echo "Boatstack shared runtime checksum is invalid; rerun the verified tagged installer." >&2
  exit 2
fi

exec "$HELPER" bootstrap-safety-hook --host "$HOST" --repo "$ROOT"
`, Version, SourceCommit, Version, SourceCommit))
}

func guardPowerShellScript() []byte {
	return []byte(fmt.Sprintf(`# Generated by Boatstack. Do not edit; change canonical source or .boatstack-project.json.
param([Parameter(Mandatory=$true)][string]$HostName)
$ErrorActionPreference = "Stop"
$root = (& git rev-parse --show-toplevel 2>$null)
if (-not $root) {
  [Console]::Error.WriteLine("Boatstack safety guard could not resolve the repository; denying tool execution.")
  exit 2
}
$common = (& git rev-parse --path-format=absolute --git-common-dir 2>$null)
if (-not $common) {
  [Console]::Error.WriteLine("Boatstack safety guard could not resolve the Git common directory; denying tool execution.")
  exit 2
}
$architecture = [System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString().ToLowerInvariant()
$arch = switch ($architecture) {
  "x64" { "amd64" }
  "arm64" { "arm64" }
  default {
    [Console]::Error.WriteLine("Boatstack safety guard found an unsupported architecture; denying tool execution.")
    exit 2
  }
}
$helper = Join-Path $common "boatstack/runtimes/%s/%s/windows-$arch/boatstack-helper.exe"
$manifestPath = Join-Path $common "boatstack/runtimes/%s/%s/windows-$arch/runtime.lock.json"
if (-not (Test-Path -LiteralPath $helper -PathType Leaf)) {
  [Console]::Error.WriteLine("Boatstack shared runtime is missing; run the verified installer once from any checkout in this Git clone.")
  exit 2
}
$helperInfo = Get-Item -LiteralPath $helper
if (($helperInfo.Attributes -band [IO.FileAttributes]::ReparsePoint) -or -not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
  [Console]::Error.WriteLine("Boatstack shared runtime is unsafe or incomplete; rerun the verified tagged installer.")
  exit 2
}
$manifestInfo = Get-Item -LiteralPath $manifestPath
if ($manifestInfo.Attributes -band [IO.FileAttributes]::ReparsePoint) {
  [Console]::Error.WriteLine("Boatstack shared runtime manifest is unsafe; rerun the verified tagged installer.")
  exit 2
}
try {
  $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json
  $actual = (Get-FileHash -LiteralPath $helper -Algorithm SHA256).Hash.ToLowerInvariant()
} catch {
  [Console]::Error.WriteLine("Boatstack could not verify the shared runtime; denying tool execution.")
  exit 2
}
if (-not $manifest.binary_sha256 -or $actual -ne $manifest.binary_sha256.ToLowerInvariant()) {
  [Console]::Error.WriteLine("Boatstack shared runtime checksum is invalid; rerun the verified tagged installer.")
  exit 2
}
& $helper bootstrap-safety-hook --host $HostName --repo $root
exit $LASTEXITCODE
`, Version, SourceCommit, Version, SourceCommit))
}

func hookCommand(host string) string {
	if host == "claude" {
		return `bash "${CLAUDE_PROJECT_DIR}/.product-loop/hooks/guard.sh" claude`
	}
	return `bash "$(git rev-parse --show-toplevel)/.product-loop/hooks/guard.sh" ` + host
}

func hookCommandWindows(host string) string {
	return `powershell -NoProfile -ExecutionPolicy Bypass -Command "$r = & git rev-parse --show-toplevel; & (Join-Path $r '.product-loop/hooks/guard.ps1') ` + host + `"`
}

func desiredHostHookForEvent(host, event string) map[string]any {
	switch host {
	case "cursor":
		entry := map[string]any{
			"command": hookCommand(host), "commandWindows": hookCommandWindows(host),
			"failClosed": true, "timeout": 10,
		}
		if event == "preToolUse" || event == "postToolUse" {
			entry["matcher"] = "Write|Edit|ApplyPatch|Create|Delete|Move|Rename"
		}
		return entry
	case "claude":
		return map[string]any{
			"matcher": "Bash|Shell|Write|Edit|ApplyPatch|Create|Delete|Move|Rename|mcp__.*",
			"hooks": []any{map[string]any{
				"type": "command", "command": hookCommand(host),
				"shell": "bash", "timeout": 10, "statusMessage": "Checking Boatstack execution policy",
			}},
		}
	case "codex":
		return map[string]any{
			"matcher": "Bash|Shell|Write|Edit|ApplyPatch|Create|Delete|Move|Rename|mcp__.*",
			"hooks": []any{map[string]any{
				"type": "command", "command": hookCommand(host), "commandWindows": hookCommandWindows(host),
				"timeout": 10, "statusMessage": "Checking Boatstack execution policy",
			}},
		}
	case "gemini":
		return map[string]any{
			"matcher": ".*", "sequential": true,
			"hooks": []any{map[string]any{
				"name": "boatstack-safety-guard", "type": "command", "command": hookCommand(host),
				"timeout": 10000, "description": "Checking Boatstack execution policy",
			}},
		}
	default:
		return map[string]any{}
	}
}

func hookEvents(host string) []string {
	if host == "cursor" {
		return []string{"preToolUse", "postToolUse", "postToolUseFailure", "beforeShellExecution", "afterShellExecution", "beforeMCPExecution", "afterMCPExecution"}
	}
	if host == "gemini" {
		return []string{"BeforeTool", "AfterTool"}
	}
	if host == "claude" {
		return []string{"PreToolUse", "PostToolUse", "PostToolUseFailure"}
	}
	return []string{"PreToolUse", "PostToolUse"}
}

func desiredHostHook(host string) map[string]any {
	return desiredHostHookForEvent(host, hookEvents(host)[0])
}

func hookFragmentJSON(host string) ([]byte, error) {
	events := map[string]any{}
	for _, event := range hookEvents(host) {
		events[event] = desiredHostHookForEvent(host, event)
	}
	return GeneratedJSON(map[string]any{"schema_version": 1, "host": host, "events": events})
}

func hostHookConfigPath(repo, host string) string {
	switch host {
	case "cursor":
		return filepath.Join(repo, ".cursor", "hooks.json")
	case "claude":
		return filepath.Join(repo, ".claude", "settings.json")
	case "codex":
		return filepath.Join(repo, ".codex", "hooks.json")
	case "gemini":
		return filepath.Join(repo, ".gemini", "settings.json")
	default:
		return ""
	}
}

func HostHookPaths(adapters []string) []string {
	paths := []string{}
	for _, host := range []string{"cursor", "claude", "codex", "gemini"} {
		if contains(adapters, host) {
			paths = append(paths, filepath.ToSlash(strings.TrimPrefix(hostHookConfigPath("", host), string(filepath.Separator))))
		}
	}
	return paths
}

func containsBoatstackHook(value any) bool {
	switch typed := value.(type) {
	case string:
		return strings.Contains(typed, hookCommandMarker)
	case []any:
		for _, item := range typed {
			if containsBoatstackHook(item) {
				return true
			}
		}
	case map[string]any:
		for _, item := range typed {
			if containsBoatstackHook(item) {
				return true
			}
		}
	}
	return false
}

func validateBoatstackHookEntry(host, event string, value any) error {
	entry, ok := value.(map[string]any)
	if !ok {
		return fmt.Errorf("%s Boatstack hook for %s is not an object", host, event)
	}
	allowedOuter := map[string]bool{}
	if host == "cursor" {
		allowedOuter = map[string]bool{"command": true, "commandWindows": true, "failClosed": true, "timeout": true, "matcher": true}
		if stringValue(entry["command"]) == "" {
			return fmt.Errorf("cursor Boatstack hook for %s has no command", event)
		}
		if entry["failClosed"] != true {
			return fmt.Errorf("cursor Boatstack hook for %s must fail closed", event)
		}
	} else {
		allowedOuter = map[string]bool{"matcher": true, "hooks": true}
		if host == "gemini" {
			allowedOuter["sequential"] = true
		}
		if stringValue(entry["matcher"]) == "" {
			return fmt.Errorf("%s Boatstack hook for %s has no matcher", host, event)
		}
		handlers, ok := entry["hooks"].([]any)
		if !ok || len(handlers) != 1 {
			return fmt.Errorf("%s Boatstack hook for %s must contain exactly one command handler", host, event)
		}
		handler, ok := handlers[0].(map[string]any)
		if !ok || handler["type"] != "command" || stringValue(handler["command"]) == "" {
			return fmt.Errorf("%s Boatstack hook for %s has an invalid command handler", host, event)
		}
		allowedHandler := map[string]bool{"type": true, "command": true, "timeout": true, "statusMessage": true}
		if host == "claude" {
			allowedHandler["shell"] = true
			// Older installed Boatstack fragments relied on Claude's Bash default.
			// Accept that structurally during update preflight, while every newly
			// generated hook pins the documented shell explicitly.
			if handler["shell"] != nil && handler["shell"] != "bash" {
				return fmt.Errorf("claude Boatstack hook for %s must use the bash harness", event)
			}
		} else if host == "codex" {
			allowedHandler["commandWindows"] = true
		} else if host == "gemini" {
			allowedHandler["name"] = true
			allowedHandler["description"] = true
		}
		for key := range handler {
			if !allowedHandler[key] {
				return fmt.Errorf("%s Boatstack hook for %s contains unsupported handler field %s", host, event, key)
			}
		}
	}
	for key := range entry {
		if !allowedOuter[key] {
			return fmt.Errorf("%s Boatstack hook for %s contains unsupported field %s", host, event, key)
		}
	}
	return nil
}

func validateHostHookConfig(host string, config map[string]any) error {
	if host == "cursor" && config["version"] != float64(1) {
		return fmt.Errorf("Cursor hook config version must be 1")
	}
	hooks, ok := config["hooks"].(map[string]any)
	if !ok {
		return fmt.Errorf("host hook config has non-object hooks")
	}
	expected := map[string]bool{}
	for _, event := range hookEvents(host) {
		expected[event] = true
	}
	for event, entries := range hooks {
		if containsBoatstackHook(entries) && !expected[event] {
			return fmt.Errorf("%s Boatstack hook is attached to unsupported event %s", host, event)
		}
	}
	return nil
}

func loadHookConfig(path string) (map[string]any, error) {
	value, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return map[string]any{}, nil
	}
	if err != nil {
		return nil, err
	}
	config := map[string]any{}
	if err := DecodeJSON("load host hook configuration", path, value, &config); err != nil {
		return nil, err
	}
	return config, nil
}

func mergeHostHook(config map[string]any, host string) error {
	return mergeHostHookWithOwnership(config, host, nil, false)
}

func mergeHostHookWithOwnership(config map[string]any, host string, installed map[string]any, repair bool) error {
	hooks, ok := config["hooks"].(map[string]any)
	if config["hooks"] == nil {
		hooks = map[string]any{}
		config["hooks"] = hooks
	} else if !ok {
		return fmt.Errorf("host hook config has non-object hooks")
	}
	desiredEvents := map[string]bool{}
	for _, event := range hookEvents(host) {
		desiredEvents[event] = true
	}
	// Retired events are an ordinary template migration when every Boatstack
	// entry exactly matches the committed fragment from the installed release.
	// The incoming helper may remove those entries before validating its own
	// event set; otherwise the updater would be blocked by the state it owns.
	for event, raw := range hooks {
		if desiredEvents[event] || !containsBoatstackHook(raw) {
			continue
		}
		entries, entriesOK := raw.([]any)
		if !entriesOK {
			return fmt.Errorf("host hook event %s is not a list", event)
		}
		kept := []any{}
		owned := 0
		verified := installed != nil && installed[event] != nil
		for _, entry := range entries {
			if !containsBoatstackHook(entry) {
				kept = append(kept, entry)
				continue
			}
			owned++
			verified = verified && sameJSON(entry, installed[event])
		}
		if owned > 0 && !verified && !repair {
			return fmt.Errorf("%s Boatstack hook is attached to unsupported event %s; rerun the update with --repair only after reviewing the owned-state preview", host, event)
		}
		if len(kept) == 0 {
			delete(hooks, event)
		} else {
			hooks[event] = kept
		}
	}
	for _, event := range hookEvents(host) {
		entries := []any{}
		if existing := hooks[event]; existing != nil {
			var entriesOK bool
			entries, entriesOK = existing.([]any)
			if !entriesOK {
				return fmt.Errorf("host hook event %s is not a list", event)
			}
		}
		kept := []any{}
		found := 0
		verified := true
		for _, entry := range entries {
			if containsBoatstackHook(entry) {
				found++
				isDesired := sameJSON(entry, desiredHostHookForEvent(host, event))
				isInstalled := installed != nil && installed[event] != nil && sameJSON(entry, installed[event])
				if installed != nil && !isDesired && !isInstalled {
					verified = false
				}
				if installed == nil {
					if err := validateBoatstackHookEntry(host, event, entry); err != nil {
						return err
					}
				}
				continue
			}
			kept = append(kept, entry)
		}
		if found > 1 && (installed == nil || !verified) && !repair {
			return fmt.Errorf("ambiguous Boatstack hook collision in %s", event)
		}
		if found > 0 && !verified && !repair {
			return fmt.Errorf("drifted %s Boatstack safety hook for %s; rerun the update with --repair only after reviewing the owned-state preview", host, event)
		}
		kept = append(kept, desiredHostHookForEvent(host, event))
		hooks[event] = kept
	}
	if host == "cursor" && config["version"] == nil {
		config["version"] = float64(1)
	}
	return validateHostHookConfig(host, config)
}

func InstallHostHooks(repo string, adapters []string) error {
	prepared, err := PrepareHostHooks(repo, adapters)
	if err != nil {
		return err
	}
	for _, path := range sortedKeys(prepared) {
		if err := atomicWrite(path, prepared[path]); err != nil {
			return err
		}
	}
	return nil
}

// PrepareHostHooks renders and validates every selected host document without
// writing, allowing initialization to fail before entering its commit phase.
func PrepareHostHooks(repo string, adapters []string) (map[string][]byte, error) {
	return prepareHostHooks(repo, adapters, false)
}

func PrepareHostHooksForUpdate(repo string, adapters []string, repair bool) (map[string][]byte, error) {
	return prepareHostHooks(repo, adapters, repair)
}

func prepareHostHooks(repo string, adapters []string, repair bool) (map[string][]byte, error) {
	prepared := map[string][]byte{}
	for _, host := range []string{"cursor", "claude", "codex", "gemini"} {
		if !contains(adapters, host) {
			continue
		}
		path := hostHookConfigPath(repo, host)
		config, err := loadHookConfig(path)
		if err != nil {
			return nil, err
		}
		var installed map[string]any
		if repair || fileExists(filepath.Join(repo, ".product-loop", "hooks", host+".fragment.json")) {
			installed, err = loadInstalledHookEvents(repo, host)
			if err != nil {
				installed, err = loadCommittedInstalledHookEvents(repo, host)
				if err != nil {
					return nil, fmt.Errorf("prepare %s host hooks: cannot verify installed ownership: %w", host, err)
				}
			}
		}
		if err := mergeHostHookWithOwnership(config, host, installed, repair); err != nil {
			return nil, fmt.Errorf("prepare %s host hooks in %s: %w", host, path, err)
		}
		value, err := MarshalJSON(config)
		if err != nil {
			return nil, fmt.Errorf("serialize merged host hook configuration %s: %w", path, err)
		}
		if err := ValidateJSON("validate merged host hook configuration", path, value); err != nil {
			return nil, err
		}
		prepared[path] = value
	}
	return prepared, nil
}

func InstallHostHooksForUpdate(repo string, adapters []string, repair bool) error {
	prepared, err := PrepareHostHooksForUpdate(repo, adapters, repair)
	if err != nil {
		return err
	}
	for _, path := range sortedKeys(prepared) {
		if err := atomicWrite(path, prepared[path]); err != nil {
			return err
		}
	}
	return nil
}

func CheckHostHooks(repo string, adapters []string) error {
	return checkHostHooks(repo, adapters, func(host, event string) (any, error) {
		return desiredHostHookForEvent(host, event), nil
	})
}

// CheckInstalledHostHooks validates merged host settings against the committed
// fragment from the installed release. Update preflight must use this boundary:
// comparing an old, healthy hook with the incoming release template would
// misclassify an intentional template migration as user drift.
func CheckInstalledHostHooks(repo string, adapters []string) error {
	for _, host := range []string{"cursor", "claude", "codex", "gemini"} {
		if !contains(adapters, host) {
			continue
		}
		installed, err := loadInstalledHookEvents(repo, host)
		if err != nil {
			installed, err = loadCommittedInstalledHookEvents(repo, host)
			if err != nil {
				return fmt.Errorf("cannot read installed %s hook fragment: %w", host, err)
			}
		}
		config, err := loadHookConfig(hostHookConfigPath(repo, host))
		if err != nil {
			return err
		}
		hooks, ok := config["hooks"].(map[string]any)
		if !ok {
			return fmt.Errorf("missing %s hooks", host)
		}
		for event, expected := range installed {
			entries, ok := hooks[event].([]any)
			if !ok {
				return fmt.Errorf("missing installed %s safety event %s", host, event)
			}
			matches := 0
			for _, entry := range entries {
				if containsBoatstackHook(entry) {
					matches++
					if !sameJSON(entry, expected) {
						return fmt.Errorf("drifted %s Boatstack safety hook", host)
					}
				}
			}
			if matches < 1 {
				return fmt.Errorf("expected an installed %s Boatstack safety hook for %s; found %d", host, event, matches)
			}
		}
		for event, raw := range hooks {
			if installed[event] == nil && containsBoatstackHook(raw) {
				return fmt.Errorf("drifted %s Boatstack safety hook on unowned event %s", host, event)
			}
		}
	}
	return nil
}

func checkHostHooks(repo string, adapters []string, expectedForEvent func(host, event string) (any, error)) error {
	for _, host := range []string{"cursor", "claude", "codex", "gemini"} {
		if !contains(adapters, host) {
			continue
		}
		path := hostHookConfigPath(repo, host)
		config, err := loadHookConfig(path)
		if err != nil {
			return err
		}
		if err := validateHostHookConfig(host, config); err != nil {
			return err
		}
		hooks, ok := config["hooks"].(map[string]any)
		if !ok {
			return fmt.Errorf("missing %s hooks in %s", host, path)
		}
		for _, event := range hookEvents(host) {
			expectedEntry, err := expectedForEvent(host, event)
			if err != nil {
				return err
			}
			if err := validateBoatstackHookEntry(host, event, expectedEntry); err != nil {
				return err
			}
			entries, ok := hooks[event].([]any)
			if !ok {
				return fmt.Errorf("missing %s safety event %s in %s", host, event, path)
			}
			matches := 0
			for _, entry := range entries {
				if containsBoatstackHook(entry) {
					matches++
					if err := validateBoatstackHookEntry(host, event, entry); err != nil {
						return err
					}
					current, _ := json.Marshal(entry)
					expected, _ := json.Marshal(expectedEntry)
					if string(current) != string(expected) {
						return fmt.Errorf("drifted %s Boatstack safety hook", host)
					}
				}
			}
			if matches != 1 {
				return fmt.Errorf("expected exactly one %s Boatstack safety hook for %s; found %d", host, event, matches)
			}
		}
	}
	return nil
}
