package boatstack

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const hookCommandMarker = ".product-loop/hooks/guard"

func guardShellScript() []byte {
	return []byte(`#!/usr/bin/env bash
# Generated by Boatstack. Do not edit; change canonical source or .boatstack-project.json.
set -u

HOST="${1:-}"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$ROOT" ]]; then
  echo "Boatstack safety guard could not resolve the repository; denying tool execution." >&2
  exit 2
fi

HELPER="$ROOT/.product-loop/bin/boatstack-helper"
if [[ ! -x "$HELPER" ]]; then
  echo "Boatstack safety helper is missing; rerun the installer from the repository root." >&2
  exit 2
fi

exec "$HELPER" safety-hook --host "$HOST" --repo "$ROOT"
`)
}

func guardPowerShellScript() []byte {
	return []byte(`# Generated by Boatstack. Do not edit; change canonical source or .boatstack-project.json.
param([Parameter(Mandatory=$true)][string]$HostName)
$ErrorActionPreference = "Stop"
$root = (& git rev-parse --show-toplevel 2>$null)
if (-not $root) {
  [Console]::Error.WriteLine("Boatstack safety guard could not resolve the repository; denying tool execution.")
  exit 2
}
$helper = Join-Path $root ".product-loop/bin/boatstack-helper.exe"
if (-not (Test-Path -LiteralPath $helper -PathType Leaf)) {
  [Console]::Error.WriteLine("Boatstack safety helper is missing; rerun the installer from the repository root.")
  exit 2
}
& $helper safety-hook --host $HostName --repo $root
exit $LASTEXITCODE
`)
}

func hookCommand(host string) string {
	return `bash "$(git rev-parse --show-toplevel)/.product-loop/hooks/guard.sh" ` + host
}

func hookCommandWindows(host string) string {
	return `powershell -NoProfile -ExecutionPolicy Bypass -Command "$r = & git rev-parse --show-toplevel; & (Join-Path $r '.product-loop/hooks/guard.ps1') ` + host + `"`
}

func desiredHostHookForEvent(host, event string) map[string]any {
	switch host {
	case "cursor":
		return map[string]any{
			"command": hookCommand(host), "commandWindows": hookCommandWindows(host),
			"failClosed": true, "timeout": 10,
		}
	case "claude":
		return map[string]any{
			"matcher": "Bash|Shell|mcp__.*",
			"hooks": []any{map[string]any{
				"type": "command", "command": hookCommand(host),
				"timeout": 10, "statusMessage": "Checking irreversible-operation policy",
			}},
		}
	case "codex":
		return map[string]any{
			"matcher": "Bash|Shell|mcp__.*",
			"hooks": []any{map[string]any{
				"type": "command", "command": hookCommand(host), "commandWindows": hookCommandWindows(host),
				"timeout": 10, "statusMessage": "Checking irreversible-operation policy",
			}},
		}
	default:
		return map[string]any{}
	}
}

func hookEvents(host string) []string {
	if host == "cursor" {
		return []string{"beforeShellExecution", "beforeMCPExecution"}
	}
	return []string{"PreToolUse"}
}

func desiredHostHook(host string) map[string]any {
	return desiredHostHookForEvent(host, hookEvents(host)[0])
}

func hookFragmentJSON(host string) ([]byte, error) {
	events := map[string]any{}
	for _, event := range hookEvents(host) {
		events[event] = desiredHostHookForEvent(host, event)
	}
	return GeneratedJSON(map[string]any{"schema_version": 1, "host": host, "events": events})
}

func hostHookConfigPath(repo, host string) string {
	switch host {
	case "cursor":
		return filepath.Join(repo, ".cursor", "hooks.json")
	case "claude":
		return filepath.Join(repo, ".claude", "settings.json")
	case "codex":
		return filepath.Join(repo, ".codex", "hooks.json")
	default:
		return ""
	}
}

func HostHookPaths(adapters []string) []string {
	paths := []string{}
	for _, host := range []string{"cursor", "claude", "codex"} {
		if contains(adapters, host) {
			paths = append(paths, filepath.ToSlash(strings.TrimPrefix(hostHookConfigPath("", host), string(filepath.Separator))))
		}
	}
	return paths
}

func containsBoatstackHook(value any) bool {
	switch typed := value.(type) {
	case string:
		return strings.Contains(typed, hookCommandMarker)
	case []any:
		for _, item := range typed {
			if containsBoatstackHook(item) {
				return true
			}
		}
	case map[string]any:
		for _, item := range typed {
			if containsBoatstackHook(item) {
				return true
			}
		}
	}
	return false
}

func loadHookConfig(path string) (map[string]any, error) {
	value, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return map[string]any{}, nil
	}
	if err != nil {
		return nil, err
	}
	config := map[string]any{}
	if err := json.Unmarshal(value, &config); err != nil {
		return nil, fmt.Errorf("invalid host hook config %s: %w", path, err)
	}
	return config, nil
}

func mergeHostHook(config map[string]any, host string) error {
	hooks, ok := config["hooks"].(map[string]any)
	if config["hooks"] == nil {
		hooks = map[string]any{}
		config["hooks"] = hooks
	} else if !ok {
		return fmt.Errorf("host hook config has non-object hooks")
	}
	for _, event := range hookEvents(host) {
		entries := []any{}
		if existing := hooks[event]; existing != nil {
			var entriesOK bool
			entries, entriesOK = existing.([]any)
			if !entriesOK {
				return fmt.Errorf("host hook event %s is not a list", event)
			}
		}
		kept := []any{}
		found := 0
		for _, entry := range entries {
			if containsBoatstackHook(entry) {
				found++
				continue
			}
			kept = append(kept, entry)
		}
		if found > 1 {
			return fmt.Errorf("ambiguous Boatstack hook collision in %s", event)
		}
		kept = append(kept, desiredHostHookForEvent(host, event))
		hooks[event] = kept
	}
	if host == "cursor" && config["version"] == nil {
		config["version"] = float64(1)
	}
	return nil
}

func InstallHostHooks(repo string, adapters []string) error {
	for _, host := range []string{"cursor", "claude", "codex"} {
		if !contains(adapters, host) {
			continue
		}
		path := hostHookConfigPath(repo, host)
		config, err := loadHookConfig(path)
		if err != nil {
			return err
		}
		if err := mergeHostHook(config, host); err != nil {
			return err
		}
		value, err := MarshalJSON(config)
		if err != nil {
			return err
		}
		if err := atomicWrite(path, value); err != nil {
			return err
		}
	}
	return nil
}

func CheckHostHooks(repo string, adapters []string) error {
	for _, host := range []string{"cursor", "claude", "codex"} {
		if !contains(adapters, host) {
			continue
		}
		path := hostHookConfigPath(repo, host)
		config, err := loadHookConfig(path)
		if err != nil {
			return err
		}
		hooks, ok := config["hooks"].(map[string]any)
		if !ok {
			return fmt.Errorf("missing %s hooks in %s", host, path)
		}
		for _, event := range hookEvents(host) {
			entries, ok := hooks[event].([]any)
			if !ok {
				return fmt.Errorf("missing %s safety event %s in %s", host, event, path)
			}
			matches := 0
			for _, entry := range entries {
				if containsBoatstackHook(entry) {
					matches++
					current, _ := json.Marshal(entry)
					expected, _ := json.Marshal(desiredHostHookForEvent(host, event))
					if string(current) != string(expected) {
						return fmt.Errorf("drifted %s Boatstack safety hook", host)
					}
				}
			}
			if matches != 1 {
				return fmt.Errorf("expected exactly one %s Boatstack safety hook for %s; found %d", host, event, matches)
			}
		}
	}
	return nil
}
