package boatstack

import "fmt"

// launcherShellScript is the tracked command boundary for POSIX worktrees. It
// resolves only the release identity baked into this generated file, verifies
// that shared runtime, asks it to activate the ignored worktree-local runtime,
// and then dispatches through the local runtime. It never searches sibling
// worktrees or selects a newer release.
func launcherShellScript() []byte {
	recovery := runtimeHydrateCommandBash(Version)
	return []byte(fmt.Sprintf(`#!/usr/bin/env bash
# Generated by Boatstack. Do not edit; change canonical source or .boatstack-project.json.
set -u

bs_fail() {
  printf 'Boatstack runtime activation failed: %%s\n' "$1" >&2
  printf 'Recovery: %%s\n' '%s' >&2
  exit 2
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" 2>/dev/null && pwd -P || true)"
[[ -n "$SCRIPT_DIR" ]] || bs_fail "cannot resolve the launcher directory"
ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || true)"
[[ -n "$ROOT" ]] || bs_fail "cannot resolve the repository"
COMMON="$(git -C "$SCRIPT_DIR" rev-parse --path-format=absolute --git-common-dir 2>/dev/null || true)"
[[ -n "$COMMON" ]] || bs_fail "cannot resolve the Git common directory"

case "$(uname -s)" in
  Darwin) OS_NAME="darwin"; EXTENSION="" ;;
  Linux) OS_NAME="linux"; EXTENSION="" ;;
  MINGW*|MSYS*|CYGWIN*) OS_NAME="windows"; EXTENSION=".exe" ;;
  *) bs_fail "unsupported operating system" ;;
esac
case "$(uname -m)" in
  x86_64|amd64) ARCH="amd64" ;;
  arm64|aarch64) ARCH="arm64" ;;
  *) bs_fail "unsupported architecture" ;;
esac

VERSION='%s'
SOURCE_COMMIT='%s'
PLATFORM="${OS_NAME}-${ARCH}"
SLOT="$COMMON/boatstack/runtimes/$VERSION/$SOURCE_COMMIT/$PLATFORM"
HELPER="$SLOT/boatstack-helper$EXTENSION"
MANIFEST="$SLOT/runtime.lock.json"
HYDRATE_LOCK="$COMMON/boatstack/hydrate-$VERSION.lock"

bs_slot_ready() {
  [[ -x "$HELPER" && ! -L "$HELPER" && -f "$MANIFEST" && ! -L "$MANIFEST" ]]
}

if ! bs_slot_ready && [[ "${BOATSTACK_AUTO_HYDRATE:-1}" != "0" ]]; then
  mkdir -p "$COMMON/boatstack" 2>/dev/null || true
  if mkdir "$HYDRATE_LOCK" 2>/dev/null; then
    if ! bs_slot_ready; then
      (
        cd "$ROOT" || exit 1
        export BOATSTACK_MODE=hydrate BOATSTACK_VERSION="$VERSION" BOATSTACK_REPO="$ROOT"
        HYDRATE_COMMAND="${BOATSTACK_HYDRATE_COMMAND:-}"
        [[ -n "$HYDRATE_COMMAND" ]] || HYDRATE_COMMAND='%s'
        if command -v timeout >/dev/null 2>&1; then
          timeout 8 /bin/bash -c "$HYDRATE_COMMAND"
        else
          /bin/bash -c "$HYDRATE_COMMAND"
        fi
      ) >&2 || true
    fi
    rmdir "$HYDRATE_LOCK" 2>/dev/null || true
  else
    for _ in $(seq 1 12); do
      [[ -d "$HYDRATE_LOCK" ]] || break
      sleep 1
    done
  fi
fi

# Path visibility is not publication. A concurrent hydrator copies the helper
# and manifest before releasing this lock, so even a ready-looking slot must
# wait for that release before its manifest is parsed.
for _ in $(seq 1 12); do
  [[ -d "$HYDRATE_LOCK" ]] || break
  sleep 1
done
[[ ! -d "$HYDRATE_LOCK" ]] || bs_fail "shared runtime hydration did not complete"

bs_slot_ready || bs_fail "the exact pinned shared runtime is missing or unsafe"
manifest_value() {
  sed -n 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$MANIFEST" | head -n 1
}
[[ "$(manifest_value boatstack_version)" == "$VERSION" ]] || bs_fail "shared runtime version does not match the launcher pin"
[[ "$(manifest_value source_commit)" == "$SOURCE_COMMIT" ]] || bs_fail "shared runtime source does not match the launcher pin"
[[ "$(manifest_value platform)" == "$PLATFORM" ]] || bs_fail "shared runtime platform does not match this host"
EXPECTED="$(manifest_value binary_sha256)"
if command -v sha256sum >/dev/null 2>&1; then
  ACTUAL="$(sha256sum "$HELPER" | awk '{print $1}')"
elif command -v shasum >/dev/null 2>&1; then
  ACTUAL="$(shasum -a 256 "$HELPER" | awk '{print $1}')"
else
  bs_fail "no SHA-256 verifier is available"
fi
[[ "$EXPECTED" =~ ^[0-9a-f]{64}$ && "$ACTUAL" == "$EXPECTED" ]] || bs_fail "shared runtime checksum is invalid"

"$HELPER" activate-worktree-runtime --repo "$ROOT" || bs_fail "the pinned runtime could not activate this worktree"
LOCAL="$ROOT/.product-loop/bin/boatstack-helper$EXTENSION"
[[ -x "$LOCAL" && ! -L "$LOCAL" ]] || bs_fail "worktree runtime activation did not produce a safe helper"
exec "$LOCAL" "$@"
`, recovery, Version, SourceCommit, recovery))
}

// launcherPowerShellScript is the PowerShell form of launcherShellScript and
// enforces the same exact identity, activation, and recovery contract.
func launcherPowerShellScript() []byte {
	recovery := runtimeHydrateCommandPowerShell(Version)
	return []byte(fmt.Sprintf(`# Generated by Boatstack. Do not edit; change canonical source or .boatstack-project.json.
$ErrorActionPreference = "Stop"
function Fail-Activation([string]$Message) {
  [Console]::Error.WriteLine("Boatstack runtime activation failed: $Message")
  [Console]::Error.WriteLine('Recovery: %s')
  exit 2
}

if (-not $PSScriptRoot) { Fail-Activation "cannot resolve the launcher directory" }
try { $root = (& git -C $PSScriptRoot rev-parse --show-toplevel 2>$null) } catch { Fail-Activation "cannot resolve the repository" }
if (-not $root) { Fail-Activation "cannot resolve the repository" }
try { $common = (& git -C $PSScriptRoot rev-parse --path-format=absolute --git-common-dir 2>$null) } catch { Fail-Activation "cannot resolve the Git common directory" }
if (-not $common) { Fail-Activation "cannot resolve the Git common directory" }
$arch = switch ([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture.ToString().ToLowerInvariant()) {
  "x64" { "amd64" }
  "arm64" { "arm64" }
  default { Fail-Activation "unsupported architecture" }
}
$version = '%s'
$sourceCommit = '%s'
$platform = "windows-$arch"
$slot = Join-Path $common "boatstack/runtimes/$version/$sourceCommit/$platform"
$helper = Join-Path $slot "boatstack-helper.exe"
$manifestPath = Join-Path $slot "runtime.lock.json"
$boatstackRoot = Join-Path $common "boatstack"
$lockPath = Join-Path $boatstackRoot "hydrate-$version.lock"
function Slot-Ready {
  (Test-Path -LiteralPath $helper -PathType Leaf) -and
  (Test-Path -LiteralPath $manifestPath -PathType Leaf) -and
  (-not ((Get-Item -LiteralPath $helper -Force).Attributes -band [IO.FileAttributes]::ReparsePoint)) -and
  (-not ((Get-Item -LiteralPath $manifestPath -Force).Attributes -band [IO.FileAttributes]::ReparsePoint))
}

if ((-not (Slot-Ready)) -and ($env:BOATSTACK_AUTO_HYDRATE -ne "0")) {
  New-Item -ItemType Directory -Force -Path $boatstackRoot | Out-Null
  $ownsLock = $false
  try { New-Item -ItemType Directory -ErrorAction Stop -Path $lockPath | Out-Null; $ownsLock = $true } catch {}
  if ($ownsLock) {
    try {
      if (-not (Slot-Ready)) {
        $env:BOATSTACK_MODE = "hydrate"
        $env:BOATSTACK_VERSION = $version
        $env:BOATSTACK_REPO = $root
        $hydrateCommand = $env:BOATSTACK_HYDRATE_COMMAND
        if (-not $hydrateCommand) { $hydrateCommand = '%s' }
        & powershell -NoProfile -Command $hydrateCommand 2>&1 | ForEach-Object { [Console]::Error.WriteLine($_) }
      }
    } catch {} finally { Remove-Item -LiteralPath $lockPath -Force -ErrorAction SilentlyContinue }
  } else {
    for ($i = 0; $i -lt 12 -and (Test-Path -LiteralPath $lockPath); $i++) { Start-Sleep -Seconds 1 }
  }
}

# File existence can become visible before the writer has finished publishing
# the manifest. Never parse shared runtime state until the writer releases the
# version-scoped hydration lock.
for ($i = 0; $i -lt 12 -and (Test-Path -LiteralPath $lockPath); $i++) { Start-Sleep -Seconds 1 }
if (Test-Path -LiteralPath $lockPath) { Fail-Activation "shared runtime hydration did not complete" }

if (-not (Slot-Ready)) { Fail-Activation "the exact pinned shared runtime is missing or unsafe" }
try { $manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json } catch { Fail-Activation "shared runtime manifest is malformed" }
if ($manifest.boatstack_version -ne $version) { Fail-Activation "shared runtime version does not match the launcher pin" }
if ($manifest.source_commit -ne $sourceCommit) { Fail-Activation "shared runtime source does not match the launcher pin" }
if ($manifest.platform -ne $platform) { Fail-Activation "shared runtime platform does not match this host" }
$actual = (Get-FileHash -LiteralPath $helper -Algorithm SHA256).Hash.ToLowerInvariant()
if (($manifest.binary_sha256 -notmatch '^[0-9a-f]{64}$') -or ($actual -ne $manifest.binary_sha256)) { Fail-Activation "shared runtime checksum is invalid" }

& $helper activate-worktree-runtime --repo $root
if ($LASTEXITCODE -ne 0) { Fail-Activation "the pinned runtime could not activate this worktree" }
$local = Join-Path $root ".product-loop/bin/boatstack-helper.exe"
if (-not (Test-Path -LiteralPath $local -PathType Leaf)) { Fail-Activation "worktree runtime activation did not produce a safe helper" }
if ($MyInvocation.ExpectingInput) {
  $input | & $local @args
} else {
  & $local @args
}
exit $LASTEXITCODE
`, recovery, Version, SourceCommit, recovery))
}
