package boatstack

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var (
	Version         = "dev"
	SourceCommit    = "unknown"
	ChecksumsSHA256 = "development"
	GStackRef       = "a3259400a366593e0c909dd9ac3e59752efd2488"
	SpecKitVersion  = "v0.12.16"
)

const (
	Generator = "boatstack-exporter"
	Marker    = "Generated by Boatstack. Do not edit; change canonical source or .boatstack-project.json."
)

//go:embed references/*.md assets/templates/*
var canonical embed.FS

type ProjectConfig struct {
	SchemaVersion int                         `json:"schema_version"`
	Project       Project                     `json:"project"`
	Workflow      Workflow                    `json:"workflow"`
	Workspace     Workspace                   `json:"workspace,omitempty"`
	Adapters      []string                    `json:"adapters"`
	Integrations  map[string]IntegrationState `json:"integrations,omitempty"`
}

type Project struct {
	Name          string            `json:"name"`
	DefaultBranch string            `json:"default_branch,omitempty"`
	Context       []string          `json:"context,omitempty"`
	Commands      map[string]string `json:"commands"`
	HighRiskPaths []string          `json:"high_risk_paths,omitempty"`
}

type Workflow struct {
	HumanPlanApproval            bool `json:"human_plan_approval"`
	IndependentReviewForHighRisk bool `json:"independent_review_for_high_risk"`
	AllowPassWithGaps            bool `json:"allow_pass_with_gaps"`
	MaintainChangelog            bool `json:"maintain_changelog"`
}

type IntegrationState struct {
	Requested bool   `json:"requested"`
	Status    string `json:"status,omitempty"`
	Version   string `json:"version,omitempty"`
	Detail    string `json:"detail,omitempty"`
}

// Workspace declares how Boatstack manages the per-feature working area: a fresh
// cut from the up-to-date default branch when a feature starts, and cleanup once
// the feature ships. The managed unit is a git worktree or an in-place branch;
// the empty zero value (Enabled=false) preserves Boatstack's prior behavior of
// never creating or removing worktrees or branches.
type Workspace struct {
	Enabled      bool   `json:"enabled,omitempty"`       // master switch; false = Boatstack touches no worktrees/branches
	Mode         string `json:"mode,omitempty"`          // "worktree" | "branch" (default "worktree")
	Cleanup      string `json:"cleanup,omitempty"`       // "confirm" | "auto" | "off" (default "confirm")
	CleanupAfter string `json:"cleanup_after,omitempty"` // "merge" | "ship" (default "merge")
}

func ReadCanonical(path string) ([]byte, error) {
	return canonical.ReadFile(path)
}

func ReadCanonicalDir(path string) ([]fs.DirEntry, error) {
	return canonical.ReadDir(path)
}

func SHA256Bytes(value []byte) string {
	digest := sha256.Sum256(value)
	return hex.EncodeToString(digest[:])
}

func SHA256File(path string) (string, error) {
	value, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	return SHA256Bytes(value), nil
}

func repositoryRelativePath(repo, target string) (string, error) {
	relative, err := filepath.Rel(repo, target)
	if err != nil {
		return "", fmt.Errorf("cannot make path repository-relative: %w", err)
	}
	if _, err := resolveRepositoryRelativePath(repo, filepath.ToSlash(relative)); err != nil {
		return "", err
	}
	return filepath.ToSlash(filepath.Clean(relative)), nil
}

func resolveRepositoryRelativePath(repo, relative string) (string, error) {
	relative = strings.TrimSpace(relative)
	if relative == "" {
		return "", fmt.Errorf("repository-relative path is empty")
	}
	native := filepath.FromSlash(relative)
	if filepath.IsAbs(native) || filepath.VolumeName(native) != "" {
		return "", fmt.Errorf("path must be repository-relative: %s", relative)
	}
	native = filepath.Clean(native)
	if native == "." || native == ".." || strings.HasPrefix(native, ".."+string(filepath.Separator)) {
		return "", fmt.Errorf("path escapes repository boundary: %s", relative)
	}
	return filepath.Join(repo, native), nil
}

func MarshalJSON(value any) ([]byte, error) {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

// DecodeJSON is the single diagnostic boundary for JSON consumed by Boatstack.
// source must name a filesystem path, embedded asset, generated destination, or
// remote response so malformed input is actionable without a debugger.
func DecodeJSON(operation, source string, raw []byte, destination any) error {
	if err := json.Unmarshal(raw, destination); err != nil {
		return fmt.Errorf("operation %s: parse JSON %s: %w", operation, source, err)
	}
	return nil
}

func ValidateJSON(operation, source string, raw []byte) error {
	var decoded any
	return DecodeJSON(operation, source, raw, &decoded)
}

func GeneratedJSON(value any) ([]byte, error) {
	raw, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	data := map[string]any{}
	if err := DecodeJSON("generate JSON metadata", "marshaled generated value", raw, &data); err != nil {
		return nil, err
	}
	data["_generated_by"] = Generator
	data["_boatstack_version"] = Version
	return MarshalJSON(data)
}

func GeneratedMarkdown(body string) []byte {
	return []byte(fmt.Sprintf("<!-- %s -->\n\n%s\n", Marker, strings.TrimSpace(body)))
}

func GeneratedFrontmatter(body string) ([]byte, error) {
	if !strings.HasPrefix(body, "---\n") {
		return nil, fmt.Errorf("frontmatter adapter must start with ---")
	}
	closing := strings.Index(body[4:], "\n---\n")
	if closing < 0 {
		return nil, fmt.Errorf("frontmatter adapter is missing its closing ---")
	}
	insertAt := 4 + closing + len("\n---\n")
	marked := body[:insertAt] + "\n<!-- " + Marker + " -->\n" + body[insertAt:]
	return []byte(strings.TrimSpace(marked) + "\n"), nil
}

func sortedKeys[T any](values map[string]T) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

func writeFile(path string, value []byte, mode fs.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, value, mode)
}
