#!/usr/bin/env python3
"""Export the canonical product loop into thin repo-specific host adapters."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


VERSION = "0.1.0"
GENERATOR = "product-engineering-loop-exporter"
ALLOWED_ADAPTERS = {"cursor", "claude", "codex", "github"}
MARKER = "Generated by product-engineering-loop exporter. Do not edit; change canonical source or project.json."
ADAPTER_NAME = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def generated_markdown(body: str) -> bytes:
    return f"<!-- {MARKER} -->\n\n{body.rstrip()}\n".encode()


def generated_frontmatter(body: str) -> bytes:
    if not body.startswith("---\n"):
        raise ValueError("frontmatter adapter must start with ---")
    closing = body.find("\n---\n", 4)
    if closing < 0:
        raise ValueError("frontmatter adapter is missing its closing ---")
    insert_at = closing + len("\n---\n")
    marked = body[:insert_at] + f"\n<!-- {MARKER} -->\n" + body[insert_at:]
    return (marked.rstrip() + "\n").encode()


def generated_script(body: str) -> bytes:
    lines = body.splitlines()
    if lines and lines[0].startswith("#!"):
        lines.insert(1, f"# {MARKER}")
    else:
        lines.insert(0, f"# {MARKER}")
    return ("\n".join(lines).rstrip() + "\n").encode()


def generated_json(value: dict) -> bytes:
    data = dict(value)
    data["_generated_by"] = GENERATOR
    data["_loop_version"] = VERSION
    return (json.dumps(data, indent=2, sort_keys=True) + "\n").encode()


def load_config(path: Path) -> dict:
    data = json.loads(path.read_text())
    if data.get("schema_version") != 1:
        raise ValueError("project config schema_version must be 1")
    project = data.get("project")
    if not isinstance(project, dict) or not project.get("name"):
        raise ValueError("project.name is required")
    commands = project.get("commands")
    if not isinstance(commands, dict) or not commands.get("test"):
        raise ValueError("project.commands.test is required; the exporter will not invent it")
    adapters = set(data.get("adapters") or ALLOWED_ADAPTERS)
    unknown = adapters - ALLOWED_ADAPTERS
    if unknown:
        raise ValueError("unsupported adapters: " + ", ".join(sorted(unknown)))
    return data


def command_body(operation: str, extra: str) -> str:
    return f"""# {operation}

Run the `{operation}` operation from `@.product-loop/workflow.md`.

Read `@.product-loop/project.json`, `@.product-loop/artifacts.md`, and only the minimal repository context relevant to the current feature. {extra}

Use the gate semantics in the canonical workflow. Do not redefine them in this adapter.
"""


def build_files(
    config_path: Path,
    config: dict,
    skill_root: Path,
    adapters: set[str],
    adapter_name: str = "product-engineering-loop",
) -> dict[Path, bytes]:
    files: dict[Path, bytes] = {}
    files[Path(".product-loop/project.json")] = generated_json(config)
    for name in ["workflow.md", "artifacts.md", "failure-moves.md"]:
        files[Path(".product-loop") / name] = generated_markdown(
            (skill_root / "references" / name).read_text()
        )
    for template in sorted((skill_root / "assets" / "templates").glob("*")):
        if template.suffix == ".json":
            value = json.loads(template.read_text())
            files[Path(".product-loop/templates") / template.name] = generated_json(value)
        else:
            files[Path(".product-loop/templates") / template.name] = generated_markdown(template.read_text())
    files[Path(".product-loop/tools/approve_plan.py")] = generated_script(
        (skill_root / "scripts" / "approve_plan.py").read_text()
    )
    files[Path(".product-loop/tools/compile_plan.py")] = generated_script(
        (skill_root / "scripts" / "compile_plan.py").read_text()
    )

    operations = {
        "auto-plan": "Produce a draft only. Do not implement and do not imply the user accepted it.",
        "plan-gate": "Require explicit human approval. Only then run `.product-loop/tools/compile_plan.py` and `.product-loop/tools/approve_plan.py` to create the executable task/evidence package and lock.",
        "build": "Before editing, locate the feature spec, plan, compiled tasks, and plan lock; run `.product-loop/tools/approve_plan.py --check` against them. Stop if it reports `BLOCKED`.",
        "test-gate": "Build a requirement-to-evidence matrix and treat self-authored tests as evidence rather than the sole oracle.",
        "review-gate": "Review the actual diff against approved intent, invariants, risks, gaps, and test evidence.",
        "ship-gate": "Prepare a PR only; do not merge or deploy without separate authorization.",
        "review": "Alias of `review-gate`: review the actual diff against approved intent, invariants, risks, gaps, and test evidence.",
        "ship": "Alias of `ship-gate`: prepare a PR only; do not merge or deploy without separate authorization.",
        "retro": "Classify evidence and propose a move; never promote it or change durable rules without a paired gate.",
    }

    if "cursor" in adapters:
        rule = """---
description: Use the canonical product engineering loop for planning, approved implementation, evidence gates, PR preparation, and loop retrospectives.
globs:
alwaysApply: false
---

The source of truth is @.product-loop/workflow.md and @.product-loop/project.json.
Use @.product-loop/artifacts.md for document meanings and @.product-loop/failure-moves.md for retrospectives.
Do not start build work until the explicit plan gate has produced a valid plan lock.
Do not branch behavior on model name, provider, or price; branch on observed work state and evidence.
"""
        files[Path(f".cursor/rules/{adapter_name}.mdc")] = generated_frontmatter(rule)
        for operation, extra in operations.items():
            files[Path(f".cursor/commands/{operation}.md")] = generated_markdown(command_body(operation, extra))

    adapter_skill = f"""---
name: {adapter_name}
description: Run the repository's canonical question-led product engineering loop for planning, explicit plan approval, implementation, test/review/ship gates, and evidence-based retrospectives.
---

# Product Engineering Loop Adapter

Read `.product-loop/project.json` and `.product-loop/workflow.md`. The requested operation is supplied by the user; valid operations are `auto-plan`, `plan-gate`, `build`, `test-gate`, `review-gate`/`review`, `ship-gate`/`ship`, and `retro`.

Use `.product-loop/artifacts.md` for document boundaries and `.product-loop/failure-moves.md` for improvement experiments. Do not implement from an unapproved or stale plan. Do not branch on model identity; use observable state and gate evidence.
"""
    if "claude" in adapters:
        files[Path(f".claude/skills/{adapter_name}/SKILL.md")] = generated_frontmatter(adapter_skill)
    if "codex" in adapters:
        files[Path(f".agents/skills/{adapter_name}/SKILL.md")] = generated_frontmatter(adapter_skill)

    if "github" in adapters:
        pr = """# Product-loop PR

## Approved intent

- Feature spec:
- Approved plan hash:
- Human approver:
- Linked ADRs/questions:

## Outcome

- User-visible change:
- Non-goals preserved:

## Gate evidence

- Test gate: `BLOCKED`
- Review gate: `BLOCKED`
- Ship gate: `BLOCKED`
- Evidence ledger:

## Known gaps

- Gap ledger:
- `PASS_WITH_GAPS` rationale, owner, and revisit trigger:

## Rollout and rollback

- Rollout:
- Observability:
- Rollback:

## Generated adapter update

- Canonical loop version:
- Config hash:
- Export check:
"""
        files[Path(f".github/PULL_REQUEST_TEMPLATE/{adapter_name}.md")] = generated_markdown(pr)

    lock_entries = {
        str(path): sha256_bytes(content) for path, content in sorted(files.items(), key=lambda item: str(item[0]))
    }
    lock = {
        "schema_version": 1,
        "generator": GENERATOR,
        "loop_version": VERSION,
        "config_source": config_path.name,
        "config_sha256": sha256_bytes(config_path.read_bytes()),
        "adapters": sorted(adapters),
        "files": lock_entries,
    }
    files[Path(".product-loop/generated.lock.json")] = generated_json(lock)
    return files


def owned(content: bytes, path: Path) -> bool:
    if MARKER.encode() in content:
        return True
    if path.suffix == ".json":
        try:
            return json.loads(content).get("_generated_by") == GENERATOR
        except (ValueError, AttributeError):
            return False
    return False


def write_files(repo: Path, files: dict[Path, bytes]) -> int:
    collisions = []
    for relative, content in files.items():
        target = repo / relative
        if target.exists() and target.read_bytes() != content and not owned(target.read_bytes(), relative):
            collisions.append(str(relative))
    if collisions:
        print("BLOCKED: refusing to overwrite user-owned files:")
        for collision in collisions:
            print(f"  {collision}")
        return 2
    for relative, content in files.items():
        target = repo / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
    print(f"wrote {len(files)} generated files to {repo}")
    return 0


def check_files(repo: Path, files: dict[Path, bytes]) -> int:
    problems = []
    for relative, content in files.items():
        target = repo / relative
        if not target.exists():
            problems.append(f"missing {relative}")
        elif target.read_bytes() != content:
            problems.append(f"drift {relative}")
    if problems:
        print("BLOCKED: generated output is stale")
        for problem in problems:
            print(f"  {problem}")
        return 1
    print(f"PASS: {len(files)} generated files match canonical source and config")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, required=True)
    parser.add_argument("--config", type=Path, required=True)
    parser.add_argument("--adapters", help="comma-separated override")
    parser.add_argument(
        "--adapter-name",
        default="product-engineering-loop",
        help="kebab-case name for generated host adapter files (default: product-engineering-loop)",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    repo = args.repo.resolve()
    config_path = args.config.resolve()
    if not repo.is_dir():
        parser.error(f"repo does not exist: {repo}")
    try:
        config = load_config(config_path)
        adapters = set(args.adapters.split(",")) if args.adapters else set(config.get("adapters") or ALLOWED_ADAPTERS)
        unknown = adapters - ALLOWED_ADAPTERS
        if unknown:
            raise ValueError("unsupported adapters: " + ", ".join(sorted(unknown)))
        if not ADAPTER_NAME.fullmatch(args.adapter_name):
            raise ValueError("adapter name must be a lowercase kebab-case slug")
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        parser.error(str(exc))

    skill_root = Path(__file__).resolve().parent.parent
    files = build_files(config_path, config, skill_root, adapters, args.adapter_name)
    if args.check:
        return check_files(repo, files)
    if args.write:
        return write_files(repo, files)
    print(f"dry run: would generate {len(files)} files in {repo}")
    for relative in sorted(files, key=str):
        print(f"  {relative}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
