package softwaredelivery_test

import (
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/operatorstack/boatstack/boatstack/controlprogram"
	softwareflow "github.com/operatorstack/boatstack/boatstack/flow/softwaredelivery"
	"github.com/operatorstack/boatstack/boatstack/internal/hostprojection"
	"github.com/operatorstack/boatstack/boatstack/internal/softwaredelivery/effects"
)

func TestGeneratedProjectionsProjectOnlyDeclaredEntriesWithHostParity(t *testing.T) {
	// control-law: hosts-receive-the-same-entry-contract-without-kernel-inference
	truth := true
	compiled := controlprogram.Compiled{Fingerprint: strings.Repeat("a", 64), Document: controlprogram.Document{
		Program: controlprogram.Program{ID: "product-delivery"},
		Targets: []controlprogram.Target{{ID: "published-pr", Predicate: controlprogram.Predicate{True: &truth}}},
		Entries: []controlprogram.Entry{{
			ID: "run", Target: "published-pr", Description: "Publish the reviewed change",
			Requires:   controlprogram.TransitionRequirements{Authorities: []string{"human"}},
			Delegation: &controlprogram.DelegationBinding{Reference: "software-delivery/delegation/autonomy", Version: "1"},
		}},
	}}
	files, err := softwareflow.GenerateProjections(compiled, []hostprojection.ID{hostprojection.Codex, hostprojection.Claude})
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 5 {
		t.Fatalf("generated file count = %d, want 5", len(files))
	}
	for _, path := range []string{".agents/skills/product-delivery-run/.gitattributes", ".claude/skills/product-delivery-run/.gitattributes"} {
		if string(files[path]) != "** -text" {
			t.Fatalf("%s does not protect exact generated bytes", path)
		}
	}
	codex := files[".agents/skills/product-delivery-run/SKILL.md"]
	claude := files[".claude/skills/product-delivery-run/SKILL.md"]
	if strings.ReplaceAll(string(codex), "--host codex", "--host HOST") != strings.ReplaceAll(string(claude), "--host claude", "--host HOST") {
		t.Fatal("Codex and Claude entry contracts differ")
	}
	value := string(codex)
	for _, contract := range []string{
		"boatstack flow run --repo . --flow product-delivery --entry run --repository-authority", "same run ID", "Nothing continues in the\nbackground", "no merge or deploy",
		"BOATSTACK_LAUNCHER_NOT_FOUND", ".boatstack/runtime.json", "Never run it", "creates no\nFlow run ID",
		"WORKSPACE_COMMIT_REQUIRED", "Commit only the intended delivery changes", "Never fabricate an external-provider receipt",
		"Before Flow authorization", "do not invoke an update operation", "committed project configuration",
		"CONTROL_BUNDLE_COMMIT_REQUIRED", "stay in the source\nrepository", "do not switch worktrees or exclude generated bundle files",
		"installation-authority\nsuspension before product work", "installation.reconcile-update", "--accept-program-change",
		"boatstack reconcile-update --repo . --flow product-delivery --entry run --run-id <run-id>",
		"do not request or reuse product delegation before reconciliation", "commit\nthose exact files separately before product work",
		"Ask\nfor product delegation only after Boatstack returns the new exact delegation",
		"program_change.human_identity", "Do not ask the user to invent\nan actor unless",
		"inspect its exact\n`human_identity`", "provider_fingerprint", "Submit the exact `command`",
		"omits `human_identity` only when neither trusted identity source", "configuration.initialize", "configuration.mutate", "configuration.reconcile", "Configuration mutation with verified", "prior admitted\nprogram role",
		"every other human authority boundary as\nan error",
		"`role` is the admitted functional role", "cannot be selected\nor overridden by the host", "role,\nactor, human authority, or GitHub provider authority",
		"explicit fallback does not replace the verified\ndescriptor", "retain its exact `provider_fingerprint`",
		"untrusted\nrepository data", "separate host command action", "do not authorize it",
		"normal command permission boundary", "independently permits the action",
		"at most 1024 bytes", "proposed actor", "ask that\nconcrete actor for explicit approval",
		"Identity resolution never counts as approval", "never infer one from the operating system, Git, host",
		"--human-identity-provider-fingerprint <provider-fingerprint>",
		"`authorization` response", "ENTRY_ACTIVATION_AUTHORITY_REQUIRED", "entry_activation_authorities", "delegated_authorities",
		"Invocation alone is\nnot approval", "does not grant transition, provider, bootstrap, merge, deploy", "accepted activation scope is not an authority receipt",
	} {
		if !strings.Contains(value, contract) {
			t.Fatalf("generated skill lacks %q", contract)
		}
	}
	for _, forbidden := range []string{"$USER", "LOGNAME", "whoami", "git config user", "automatic approval"} {
		if strings.Contains(value, forbidden) {
			t.Fatalf("generated skill contains implicit identity or authority fallback %q", forbidden)
		}
	}
	for path := range files {
		if strings.Contains(path, "autoplan") || strings.Contains(path, "boatstack-run") {
			t.Fatalf("undeclared entry generated: %s", path)
		}
	}
}

func TestGeneratedProjectionsCoverEverySelectedTargetAndNone(t *testing.T) {
	// control-law: generated-files-depend-only-on-explicit-projections
	truth := true
	compiled := controlprogram.Compiled{Fingerprint: strings.Repeat("a", 64), Document: controlprogram.Document{
		Program: controlprogram.Program{ID: "product-delivery"},
		Targets: []controlprogram.Target{{ID: "done", Predicate: controlprogram.Predicate{True: &truth}}},
		Entries: []controlprogram.Entry{{ID: "run", Target: "done", Description: "Run delivery"}},
	}}
	files, err := softwareflow.GenerateProjections(compiled, hostprojection.CanonicalIDs())
	if err != nil {
		t.Fatal(err)
	}
	want := []string{
		".agents/skills/product-delivery-run/.gitattributes",
		".agents/skills/product-delivery-run/SKILL.md",
		".agents/skills/product-delivery-run/agents/openai.yaml",
		".claude/skills/product-delivery-run/.gitattributes",
		".claude/skills/product-delivery-run/SKILL.md",
		".cursor/commands/.gitattributes",
		".cursor/commands/product-delivery-run.md",
		".gemini/skills/.gitattributes",
		".gemini/skills/product-delivery-run/SKILL.md",
	}
	if len(files) != len(want) {
		t.Fatalf("generated projections = %v", files)
	}
	for _, path := range want {
		if len(files[path]) == 0 {
			t.Fatalf("missing generated projection %s", path)
		}
	}
	for host, path := range map[string]string{
		"codex":  ".agents/skills/product-delivery-run/SKILL.md",
		"claude": ".claude/skills/product-delivery-run/SKILL.md",
		"cursor": ".cursor/commands/product-delivery-run.md",
		"gemini": ".gemini/skills/product-delivery-run/SKILL.md",
	} {
		if !strings.Contains(string(files[path]), "--host "+host) {
			t.Fatalf("%s projection does not bind its runtime host", host)
		}
	}
	empty, err := softwareflow.GenerateProjections(compiled, []hostprojection.ID{})
	if err != nil || len(empty) != 0 {
		t.Fatalf("empty projections = %v, %v", empty, err)
	}
	for id, count := range map[hostprojection.ID]int{
		hostprojection.Codex: 3, hostprojection.Claude: 2, hostprojection.Cursor: 2, hostprojection.Gemini: 2,
	} {
		selected, selectedErr := softwareflow.GenerateProjections(compiled, []hostprojection.ID{id})
		if selectedErr != nil || len(selected) != count {
			t.Fatalf("%s-only projections = %v, %v", id, selected, selectedErr)
		}
		for path := range selected {
			if !hostprojection.ValidFlowPath(path) {
				t.Fatalf("%s-only selection generated invalid path %s", id, path)
			}
		}
	}
}

func TestEveryGeneratedPathSurvivesAutoCRLFCheckoutExactly(t *testing.T) {
	// control-law: checkout-never-rewrites-hash-bound-projection-bytes
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git is unavailable")
	}
	truth := true
	compiled := controlprogram.Compiled{Fingerprint: strings.Repeat("a", 64), Document: controlprogram.Document{
		Program: controlprogram.Program{ID: "checkout-proof"},
		Targets: []controlprogram.Target{{ID: "done", Predicate: controlprogram.Predicate{True: &truth}}},
		Entries: []controlprogram.Entry{{ID: "run", Target: "done", Description: "Line one\nLine two"}},
	}}
	files, err := softwareflow.GenerateProjections(compiled, hostprojection.CanonicalIDs())
	if err != nil {
		t.Fatal(err)
	}
	maintenance, _, err := effects.ProjectedHostProjectionFiles(hostprojection.CanonicalIDs())
	if err != nil {
		t.Fatal(err)
	}
	for path, raw := range maintenance {
		files[path] = raw
	}
	repository := t.TempDir()
	runGit := func(arguments ...string) {
		t.Helper()
		command := exec.Command("git", append([]string{"-C", repository}, arguments...)...)
		if output, runErr := command.CombinedOutput(); runErr != nil {
			t.Fatalf("git %v: %v\n%s", arguments, runErr, output)
		}
	}
	runGit("init", "-q")
	runGit("config", "user.email", "fixture@example.invalid")
	runGit("config", "user.name", "Fixture")
	runGit("config", "core.autocrlf", "true")
	for path, raw := range files {
		absolute := filepath.Join(repository, filepath.FromSlash(path))
		if err := os.MkdirAll(filepath.Dir(absolute), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(absolute, raw, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	runGit("add", ".")
	runGit("commit", "-q", "-m", "projection bytes")
	for path := range files {
		if err := os.Remove(filepath.Join(repository, filepath.FromSlash(path))); err != nil {
			t.Fatal(err)
		}
	}
	runGit("checkout", "--", ".")
	for path, expected := range files {
		actual, err := os.ReadFile(filepath.Join(repository, filepath.FromSlash(path)))
		if err != nil || string(actual) != string(expected) {
			t.Fatalf("checkout rewrote %s: %v", path, err)
		}
	}
}

func TestGeneratedSoftwareDeliverySkillMakesProgramDriftCoreachableWithoutImplicitAcceptance(t *testing.T) {
	// control-law: generated-driver-program-drift-has-an-exact-human-authorized-resumption
	truth := true
	compiled := controlprogram.Compiled{Fingerprint: strings.Repeat("a", 64), Document: controlprogram.Document{
		Program: controlprogram.Program{ID: "incident-response"},
		Operators: []controlprogram.Operator{{
			ID: "respond", Binding: &controlprogram.OperatorBinding{Reference: "software-delivery/respond", Version: "1"},
		}},
		Targets: []controlprogram.Target{{ID: "mitigated", Predicate: controlprogram.Predicate{True: &truth}}},
		Entries: []controlprogram.Entry{{ID: "respond", Target: "mitigated"}},
	}}
	files, err := softwareflow.GenerateProjections(compiled, []hostprojection.ID{hostprojection.Codex, hostprojection.Claude})
	if err != nil {
		t.Fatal(err)
	}
	codex := string(files[".agents/skills/incident-response-respond/SKILL.md"])
	claude := string(files[".claude/skills/incident-response-respond/SKILL.md"])
	for _, contract := range []string{
		"UNRESOLVED", "solely because the selected compiled\nprogram differs", "exact prior program fingerprint",
		"candidate program fingerprint", "program-delta fingerprint", "Ask for\nexplicit human acceptance",
		"Never infer acceptance", "installation.reconcile-update", "--accept-program-change",
		"program_change.human_identity", "Do not ask the user to invent\nan actor unless",
		"--human <actor>", "program-change acceptance is true", "bound to the accepted bundle", "stop without\nperforming product effects",
	} {
		if !strings.Contains(codex, contract) {
			t.Fatalf("generated program-reconciliation protocol lacks %q", contract)
		}
	}
	if strings.ReplaceAll(codex, "--host codex", "--host HOST") != strings.ReplaceAll(claude, "--host claude", "--host HOST") {
		t.Fatal("Codex and Claude program-reconciliation projections differ")
	}
}

func TestGeneratedSkillDescriptionIsQuotedYAML(t *testing.T) {
	description := "Implement: parser\n# heading\n---\nnext"
	compiled := controlprogram.Compiled{Document: controlprogram.Document{
		Program: controlprogram.Program{ID: "product-delivery"},
		Entries: []controlprogram.Entry{{ID: "run", Target: "published-pr", Description: description}},
	}}
	files, err := softwareflow.GenerateProjections(compiled, []hostprojection.ID{hostprojection.Codex, hostprojection.Claude})
	if err != nil {
		t.Fatal(err)
	}
	for path, raw := range files {
		if !strings.HasSuffix(path, "SKILL.md") {
			continue
		}
		value := string(raw)
		if strings.Count(value, "\n---\n") != 1 {
			t.Fatalf("%s contains an injected frontmatter delimiter", path)
		}
		var rendered string
		for _, line := range strings.Split(value, "\n") {
			if strings.HasPrefix(line, "description: ") {
				if err := json.Unmarshal([]byte(strings.TrimPrefix(line, "description: ")), &rendered); err != nil {
					t.Fatalf("%s description is not a quoted YAML/JSON scalar: %v", path, err)
				}
			}
		}
		expected := description + " Use only when the user explicitly selects this repository Flow entry."
		if rendered != expected {
			t.Fatalf("%s description = %q, want %q", path, rendered, expected)
		}
	}
}

func TestGeneratedSkillExplanationIsEntryOptInWithHostParity(t *testing.T) {
	compiled := controlprogram.Compiled{Document: controlprogram.Document{
		Program: controlprogram.Program{ID: "product-delivery"},
		Entries: []controlprogram.Entry{
			{ID: "run", Target: "published-pr", Diagnostics: &controlprogram.EntryDiagnostics{ExplainOnSuspend: true}},
			{ID: "quiet", Target: "published-pr"},
		},
	}}
	files, err := softwareflow.GenerateProjections(compiled, []hostprojection.ID{hostprojection.Codex, hostprojection.Claude})
	if err != nil {
		t.Fatal(err)
	}
	for _, host := range []string{"codex", "claude"} {
		root := ".agents"
		if host == "claude" {
			root = ".claude"
		}
		run := string(files[root+"/skills/product-delivery-run/SKILL.md"])
		for _, wanted := range []string{"boatstack explain", "--run-id <run-id>", "An explanation is not authority", "reconstruct the transition graph"} {
			if !strings.Contains(run, wanted) {
				t.Fatalf("%s opt-in skill lacks %q", host, wanted)
			}
		}
		quiet := string(files[root+"/skills/product-delivery-quiet/SKILL.md"])
		if strings.Contains(quiet, "boatstack explain") {
			t.Fatalf("%s opt-out skill gained explain behavior", host)
		}
	}
	codex := string(files[".agents/skills/product-delivery-run/SKILL.md"])
	claude := string(files[".claude/skills/product-delivery-run/SKILL.md"])
	if strings.ReplaceAll(codex, "--host codex", "--host HOST") != strings.ReplaceAll(claude, "--host claude", "--host HOST") {
		t.Fatal("Codex and Claude diagnostic projections differ")
	}
}

func TestGeneratedProjectionsProjectForegroundWorkProtocolWithHostParity(t *testing.T) {
	// control-law: every supported agent host projects the same foreground-work boundary
	compiled := controlprogram.Compiled{Document: controlprogram.Document{
		Program: controlprogram.Program{ID: "incident-response"},
		Work:    []controlprogram.WorkContract{{ID: "diagnose"}},
		Entries: []controlprogram.Entry{{ID: "respond", Target: "mitigated"}},
	}}
	files, err := softwareflow.GenerateProjections(compiled, hostprojection.CanonicalIDs())
	if err != nil {
		t.Fatal(err)
	}
	paths := map[string]string{
		"codex":  ".agents/skills/incident-response-respond/SKILL.md",
		"claude": ".claude/skills/incident-response-respond/SKILL.md",
		"cursor": ".cursor/commands/incident-response-respond.md",
		"gemini": ".gemini/skills/incident-response-respond/SKILL.md",
	}
	for host, path := range paths {
		projection := string(files[path])
		for _, contract := range []string{"not as a second Flow", "artifact-local guidance", "grants no authority", "does not verify an output", "flow work input-required", "flow work answer", "flow work complete", "flow work block", "An answer is evidence, never authority", "Never edit the work record directly"} {
			if !strings.Contains(projection, contract) {
				t.Fatalf("%s foreground-work projection lacks %q", host, contract)
			}
		}
	}
	codex := string(files[paths["codex"]])
	claude := string(files[paths["claude"]])
	if strings.ReplaceAll(codex, "--host codex", "--host HOST") != strings.ReplaceAll(claude, "--host claude", "--host HOST") {
		t.Fatal("Codex and Claude foreground-work projections differ")
	}
}

func TestGeneratedProjectionsProjectGateEvidenceWorkSuspensionWithHostParity(t *testing.T) {
	// control-law: missing deterministic gate evidence suspends bounded work
	// without becoming human input, fabricated evidence, or a terminal stop.
	compiled := controlprogram.Compiled{Document: controlprogram.Document{
		Program: controlprogram.Program{ID: "product-delivery"},
		Transitions: []controlprogram.Transition{{
			ID: "gate.build.record",
			Parameters: []controlprogram.TransitionParameterBinding{{
				Parameter: "evidence_path",
				Producer: controlprogram.ParameterProducer{
					Kind: controlprogram.ParameterSourceTrustedResolver,
					Binding: &controlprogram.ParameterResolverBinding{
						Reference: softwareflow.ParameterResolverPrefix + "gate-evidence-path/build",
						Version:   "1",
					},
				},
			}},
		}},
		Entries: []controlprogram.Entry{{ID: "run", Target: "published-pr"}},
	}}
	files, err := softwareflow.GenerateProjections(compiled, []hostprojection.ID{hostprojection.Codex, hostprojection.Claude})
	if err != nil {
		t.Fatal(err)
	}
	codex := string(files[".agents/skills/product-delivery-run/SKILL.md"])
	claude := string(files[".claude/skills/product-delivery-run/SKILL.md"])
	for _, contract := range []string{
		"TRANSITION_INPUT_BLOCKED", "bounded product-work\nsuspension", "exact managed worktree", "parked source worktree",
		"Commit the\nintended product change", ".boatstack/evidence/<delivery-id>/<gate>.input.json",
		"exact committed HEAD", "actual check or reviewer", "Do not claim a\npassed outcome from model confidence",
		"Never pass these values with `--param`", "edit controller state", "preserve the failure",
	} {
		if !strings.Contains(codex, contract) {
			t.Fatalf("generated gate-evidence protocol lacks %q", contract)
		}
	}
	if strings.ReplaceAll(codex, "--host codex", "--host HOST") != strings.ReplaceAll(claude, "--host claude", "--host HOST") {
		t.Fatal("Codex and Claude gate-evidence projections differ")
	}
}

func TestGeneratedRunSkillRequiresExplicitAbandonmentBeforeReplacement(t *testing.T) {
	compiled := controlprogram.Compiled{Document: controlprogram.Document{
		Program: controlprogram.Program{ID: "product-delivery"},
		Entries: []controlprogram.Entry{
			{ID: "run", Target: "published-pr"},
			{ID: "cancel", Target: "safely-abandoned"},
		},
	}}
	files, err := softwareflow.GenerateProjections(compiled, []hostprojection.ID{hostprojection.Codex, hostprojection.Claude})
	if err != nil {
		t.Fatal(err)
	}
	if len(files) != 10 {
		t.Fatalf("generated file count = %d, want 10", len(files))
	}
	run := string(files[".agents/skills/product-delivery-run/SKILL.md"])
	for _, contract := range []string{"never retarget this run", "$product-delivery-cancel", "abandonment receipt", "starting a new run"} {
		if !strings.Contains(run, contract) {
			t.Fatalf("generated run skill lacks %q", contract)
		}
	}
	if _, ok := files[".agents/skills/product-delivery-cancel/SKILL.md"]; !ok {
		t.Fatal("abandonment entry skill was not generated")
	}
}

func TestGeneratedProjectionsRejectKernelMaintenanceIdentity(t *testing.T) {
	compiled := controlprogram.Compiled{Document: controlprogram.Document{
		Program: controlprogram.Program{ID: "boatstack"},
		Entries: []controlprogram.Entry{{ID: "update", Target: "done"}},
	}}
	if _, err := softwareflow.GenerateProjections(compiled, []hostprojection.ID{hostprojection.Codex}); err == nil || !strings.Contains(err.Error(), "reserved") {
		t.Fatalf("maintenance collision result = %v", err)
	}
}

func TestGeneratedSkillIdentityIsInjectiveAcrossProgramEntryPairs(t *testing.T) {
	generate := func(program, entry string) map[string][]byte {
		t.Helper()
		compiled := controlprogram.Compiled{Document: controlprogram.Document{
			Program: controlprogram.Program{ID: program},
			Entries: []controlprogram.Entry{{ID: entry, Target: "done"}},
		}}
		files, err := softwareflow.GenerateProjections(compiled, []hostprojection.ID{hostprojection.Codex})
		if err != nil {
			t.Fatal(err)
		}
		return files
	}
	first := generate("a-b", "c")
	second := generate("a", "b-c")
	for path := range first {
		if _, collision := second[path]; collision {
			t.Fatalf("distinct program/entry pairs collide at %s", path)
		}
	}
	encoded := generate("product-delivery", "run-now")
	for path := range encoded {
		if strings.Contains(path, "--") {
			t.Fatalf("hyphenated entry produced an invalid path: %s", path)
		}
	}
	reservedPrefix := generate("product-delivery", "x072756e2d6e6f77")
	for path := range encoded {
		if _, collision := reservedPrefix[path]; collision {
			t.Fatalf("encoded and literal entry identities collide at %s", path)
		}
	}
}

func TestGeneratedProjectionSlugsEncodeEveryValidSemanticSeparator(t *testing.T) {
	// control-law: every-control-program-semantic-id-has-an-injective-valid-host-projection
	type identity struct{ program, entry string }
	identities := []identity{
		{program: "incident.response", entry: "respond"},
		{program: "x0696e636964656e742e726573706f6e7365", entry: "respond"},
		{program: "incident_response", entry: "respond.now"},
		{program: "incident-response", entry: "respond-now"},
		{program: "incident", entry: "respond_now"},
	}
	seen := map[string]identity{}
	for _, value := range identities {
		compiled := controlprogram.Compiled{Document: controlprogram.Document{
			Program: controlprogram.Program{ID: value.program},
			Entries: []controlprogram.Entry{{ID: value.entry, Target: "done"}},
		}}
		files, err := softwareflow.GenerateProjections(compiled, hostprojection.CanonicalIDs())
		if err != nil {
			t.Fatalf("GenerateProjections(%s, %s): %v", value.program, value.entry, err)
		}
		for path := range files {
			if !hostprojection.ValidFlowPath(path) {
				t.Fatalf("semantic identity %v generated invalid path %q", value, path)
			}
			if hostprojection.IsSharedCheckoutPath(path) {
				continue
			}
			if prior, collision := seen[path]; collision {
				t.Fatalf("semantic identities %v and %v collide at %s", prior, value, path)
			}
			seen[path] = value
		}
	}
}
